import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Provider from "@/lib/authProvider";
import Profile from "./Profile";
import CategoryList from "@/components/category-list";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <main>
              <div className="flex items-center justify-between">
                <h1>Collector.</h1>
                <Profile />
              </div>
              <Suspense fallback={<p>Loading...</p>}>
                <CategoryList />
              </Suspense>
              {children}
            </main>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
