import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Provider from "@/lib/authProvider";
import Profile from "./Profile";
import CategoryList from "@/components/category-list";
import { Suspense } from "react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Icons } from "@/components/Icons";
import ReactQueryProvider from "@/lib/queryProider";
import { Toaster } from "@/components/ui/toaster";
import { vina } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <ReactQueryProvider>
              <main>
                <div className="flex items-center justify-between">
                  <h1 className={`${vina.className} text-5xl`}>Collector.</h1>
                  <Profile />
                </div>
                {/* <Suspense
                fallback={
                  
                }
              > */}
                <CategoryList />
                {/* </Suspense> */}
                {children}
              </main>
              <Toaster />
            </ReactQueryProvider>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
